global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:5044']
  - job_name: 'elasticsearch'
    metrics_path: "/_prometheus/metrics"
    static_configs:
      - targets: ['elasticsearch:9200']
  - job_name: 'aap-controller'
    metrics_path: "/api/controller/v2/metrics/"
    static_configs:
      - targets: ['aap:443']
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: "admin"
      password: ""
