global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:5044']
  - job_name: 'elasticsearch'
    metrics_path: "/_prometheus/metrics"
    static_configs:
      - targets: ['elasticsearch:9200']

